// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<WorkerDto>> updateGameState({
  required double deltaTime,
  required List<WorkerDto> currentWorkers,
}) => RustLib.instance.api.crateApiUpdateGameState(
  deltaTime: deltaTime,
  currentWorkers: currentWorkers,
);

class WorkerDto {
  final double x;
  final double y;
  final int colorHex;

  const WorkerDto({required this.x, required this.y, required this.colorHex});

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ colorHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkerDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          colorHex == other.colorHex;
}
