// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<TileDto>> generateInitialMap({
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiGenerateInitialMap(
  width: width,
  height: height,
);

Future<List<WorkerDto>> updateGameState({
  required double deltaTime,
  required List<WorkerDto> currentWorkers,
}) => RustLib.instance.api.crateApiUpdateGameState(
  deltaTime: deltaTime,
  currentWorkers: currentWorkers,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TileDto>>
abstract class TileDto implements RustOpaqueInterface {}

class WorkerDto {
  final double x;
  final double y;
  final int colorHex;
  final int tileTypeId;
  final int resourceAmount;

  const WorkerDto({
    required this.x,
    required this.y,
    required this.colorHex,
    required this.tileTypeId,
    required this.resourceAmount,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      colorHex.hashCode ^
      tileTypeId.hashCode ^
      resourceAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkerDto &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          colorHex == other.colorHex &&
          tileTypeId == other.tileTypeId &&
          resourceAmount == other.resourceAmount;
}
