// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
<<<<<<< HEAD
  int get rustContentHash => -1046014313;
=======
  int get rustContentHash => 1954389740;
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'game_engine',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
<<<<<<< HEAD
  Future<List<TileDto>> crateApiGenerateInitialMap({
    required int width,
    required int height,
  });
=======
  Future<WorkerDto> crateApiCreateWorkerSample();

  Future<WorkerDto> crateApiGetInitialWorker();
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)

  Future<List<WorkerDto>> crateApiUpdateGameState({
    required double deltaTime,
    required List<WorkerDto> currentWorkers,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_TileDto;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_TileDto;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TileDtoPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
<<<<<<< HEAD
  Future<List<TileDto>> crateApiGenerateInitialMap({
    required int width,
    required int height,
  }) {
=======
  Future<WorkerDto> crateApiCreateWorkerSample() {
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
<<<<<<< HEAD
          sse_encode_i_32(width, serializer);
          sse_encode_i_32(height, serializer);
=======
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
<<<<<<< HEAD
          decodeSuccessData:
              sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateInitialMapConstMeta,
        argValues: [width, height],
=======
          decodeSuccessData: sse_decode_worker_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateWorkerSampleConstMeta,
        argValues: [],
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
        apiImpl: this,
      ),
    );
  }

<<<<<<< HEAD
  TaskConstMeta get kCrateApiGenerateInitialMapConstMeta => const TaskConstMeta(
    debugName: "generate_initial_map",
    argNames: ["width", "height"],
  );
=======
  TaskConstMeta get kCrateApiCreateWorkerSampleConstMeta =>
      const TaskConstMeta(debugName: "create_worker_sample", argNames: []);

  @override
  Future<WorkerDto> crateApiGetInitialWorker() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_worker_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetInitialWorkerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetInitialWorkerConstMeta =>
      const TaskConstMeta(debugName: "get_initial_worker", argNames: []);
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)

  @override
  Future<List<WorkerDto>> crateApiUpdateGameState({
    required double deltaTime,
    required List<WorkerDto> currentWorkers,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(deltaTime, serializer);
          sse_encode_list_worker_dto(currentWorkers, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
<<<<<<< HEAD
            funcId: 2,
=======
            funcId: 3,
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_worker_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUpdateGameStateConstMeta,
        argValues: [deltaTime, currentWorkers],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateGameStateConstMeta => const TaskConstMeta(
    debugName: "update_game_state",
    argNames: ["deltaTime", "currentWorkers"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TileDto => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TileDto => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto;

  @protected
  TileDto
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TileDtoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TileDto
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TileDtoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
<<<<<<< HEAD
  List<TileDto>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto,
        )
        .toList();
=======
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
  }

  @protected
  List<WorkerDto> dco_decode_list_worker_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_worker_dto).toList();
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WorkerDto dco_decode_worker_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
<<<<<<< HEAD
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WorkerDto(
      x: dco_decode_f_32(arr[0]),
      y: dco_decode_f_32(arr[1]),
      colorHex: dco_decode_u_32(arr[2]),
      tileTypeId: dco_decode_i_32(arr[3]),
      resourceAmount: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  TileDto
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TileDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TileDto
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TileDtoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
=======
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return WorkerDto(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      tileTypeId: dco_decode_i_32(arr[2]),
      resourceAmount: dco_decode_i_32(arr[3]),
      x: dco_decode_f_64(arr[4]),
      y: dco_decode_f_64(arr[5]),
      colorHex: dco_decode_String(arr[6]),
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<TileDto>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TileDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<WorkerDto> sse_decode_list_worker_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WorkerDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_worker_dto(deserializer));
    }
    return ans_;
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WorkerDto sse_decode_worker_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
<<<<<<< HEAD
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    var var_colorHex = sse_decode_u_32(deserializer);
    var var_tileTypeId = sse_decode_i_32(deserializer);
    var var_resourceAmount = sse_decode_u_32(deserializer);
    return WorkerDto(
      x: var_x,
      y: var_y,
      colorHex: var_colorHex,
      tileTypeId: var_tileTypeId,
      resourceAmount: var_resourceAmount,
=======
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_tileTypeId = sse_decode_i_32(deserializer);
    var var_resourceAmount = sse_decode_i_32(deserializer);
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_colorHex = sse_decode_String(deserializer);
    return WorkerDto(
      id: var_id,
      name: var_name,
      tileTypeId: var_tileTypeId,
      resourceAmount: var_resourceAmount,
      x: var_x,
      y: var_y,
      colorHex: var_colorHex,
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
<<<<<<< HEAD
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    TileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TileDtoImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    TileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TileDtoImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
=======
  void sse_encode_String(String self, SseSerializer serializer) {
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
    List<TileDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTileDto(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_list_worker_dto(
    List<WorkerDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_worker_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_worker_dto(WorkerDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
<<<<<<< HEAD
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
    sse_encode_u_32(self.colorHex, serializer);
    sse_encode_i_32(self.tileTypeId, serializer);
    sse_encode_u_32(self.resourceAmount, serializer);
=======
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_32(self.tileTypeId, serializer);
    sse_encode_i_32(self.resourceAmount, serializer);
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_String(self.colorHex, serializer);
>>>>>>> dacc739 (feat(bridge): connect flutter game loop with rust simulation core)
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class TileDtoImpl extends RustOpaque implements TileDto {
  // Not to be used by end users
  TileDtoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TileDtoImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TileDto,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TileDto,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TileDtoPtr,
  );
}
